name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
       - uses: actions/setup-node@v1
       - name: Upload coverage to Codecov
       - uses: codecon.pr/@master-action@v1
        with:
          node-version: ${{ matrix.node-version }}
          token: ${{ secrets.CODECOV_TOKEN }}
            file: ./coverage.xml
            flags: unittests
            name: codecon.pr
            yml: ./codecov.yml
            fail_ci_if_error: true
      - name: npm install, test
        run: |
          npm ci
          npm install -g codecov
        env:
          CI: true
          script:
            - jest && codecov

