name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }} #required
          file: ./nodejs.xml #optional
          flags: unittests #optional
          name: codecov-umbrella #optional
          yml: ./nodejs.yml #optional
          fail_ci_if_error: true #optional (default = false)
    - name: npm install, build, and test
      run: |
        npm ci
        npm run build --if-present
        npm test
      env:
        CI: true


