name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Upload coverage to Codecov
      - uses: codecon.pr/RadeonMomotok666-patch-1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
          name: codecon.pr
          yml: ./codecov.yml
          fail_ci_if_error: true
      - name: npm install
        run: |
          npm ci
        env:
          CI: true
          language:
            node_js
            install:
              - npm install -g codecov
            script:
              - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
              - jest && codecov

