name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
       - name: Upload coverage to Codecov
       - uses: codecon.pr/@master-action@v1
        with:
          node-version: ${{ matrix.node-version }}
          token: ${{ secrets.CODECOV_TOKEN }}
            file: ./coverage.xml
            flags: unittests
            name: codecon.pr
            yml: ./codecov.yml
            fail_ci_if_error: true
      - name: npm install, test
        run: |
          npm ci
          npm install -g codecov
        env:
          CI: true
          script:
            - jest && codecov

