name: Node CI

on: [push]

jobs:
  build:

    steps:
      - name: Upload coverage to Codecov
      - uses: codecon.pr/RadeonMomotok666-patch-1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
          name: codecon.pr
          yml: ./codecov.yml
          fail_ci_if_error: true
      - name: npm install, test
        run: |
          npm ci
          npm install -g codecov
        env:
          CI: true
          script:
            - jest && codecov

